#
# Copyright (C) 2025  CismonX <admin@cismon.net>
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty, provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
#

image: debian/stable
packages: [
  # build
  autoconf, automake, libtool, pkgconf, make, gcc, g++, texinfo, dejagnu,
  # libs
  libreadline-dev, librime-dev,
]
sources:
  - https://git.sr.ht/~cismonx/arif
environment:
  C_CXX_FLAGS: >-
    -O0 -g -Wall -Wextra -Wpedantic -Wshadow
    -fsanitize=address,undefined -fno-sanitize-recover
  # tinfo.pc (dependency of readline) defines these, but we don't need them.
  UNDEF_FLAGS: -U_DEFAULT_SOURCE -U_XOPEN_SOURCE
tasks:
  - setup: |
      mkdir arif/build && cd arif/build
      autoreconf -i ..
      ../configure --enable-arif-debug --enable-arif-rime --enable-rl-loop   \
          CFLAGS="-std=c99 $C_CXX_FLAGS" CXXFLAGS="-std=c++98 $C_CXX_FLAGS"  \
          CPPFLAGS="$UNDEF_FLAGS -D_POSIX_C_SOURCE=200112L"
  - build: |
      cd arif/build
      make
  - test: |
      cd arif/build
      make check

# For history builds, see: <https://builds.sr.ht/~cismonx/arif>
