#
# Copyright (C) 2023  CismonX <admin@cismon.net>
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty, provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
#

# For history build logs, see <https://ci.cismon.net/repos/cismonx/arif>.

steps:
  - name: build
    image: debian:bookworm-slim
    when:
      - event: [push, tag, manual]
        branch: master
    commands:
      - apt-get -y update && apt-get -y install
            gcc g++ make pkgconf autoconf automake libtool
            autoconf-archive dejagnu texinfo libreadline-dev librime-dev
      - mkdir build && cd build && autoreconf -i ..
      - ../configure --with-readline --with-rime
            --enable-arif-debug --enable-arify --enable-rl-loop
            CFLAGS='-O0 -g -std=c99 -Wall -Wextra -Wpedantic -Wshadow'
            CPPFLAGS='-D_POSIX_C_SOURCE=200112L'
      - make
      - make check
      - make dist
