.TH ARIFY 1 "Jan 02, 2023" 0.1.0 "ARIF User Manual"
.
.SH NAME
arify - execute program with input methods
.
.SH SYNOPSIS
.B arify
.RI [ options ]
.I pathname
.RI [ args ]
.
.SH DESCRIPTION
Executes the program referred to by
.IR pathname ,
passing
.I args
as its command-line arguments.
.PP
If the program uses a line editor supported by ARIF,
it will be provided with the ability to interact with input method engines.
The exact behaviour depends on the frontend specified.
.
.SH OPTIONS
.TP
\fB\-e\fR \fIengines\fR
Overrides the
.B ARIFY_ENGINES
environment variable with
.IR engines .
.IP
If multiple
.B \-e
options are provided, the resulting value is a concatenation of each
.IR engines ,
with an ASCII Space character as separator.
.TP
\fB\-f\fR \fIfrontend\fR
Overrides the
.B ARIFY_FRONTEND
environment variable with
.IR frontend .
.TP
\fB\-l\fR \fIlog-file\fR
Overrides the
.B ARIFY_LOG_FILE
environment variable with
.IR log-file .
.TP
\fB\-n\fR \fIpage-size\fR
Overrides the
.B ARIFY_PAGE_SIZE
environment variable with
.IR page-size .
.TP
\fB\-p\fR \fIpreload-library\fR
Path to the preload library (e.g. "/usr/local/lib/libarify.so").
.IP
Default value depends on the specified install directory when building ARIF.
.TP
\fB\-V\fR
Prints the version number of ARIF, and then exits.
.
.SH EXIT STATUS
If an error occurs before
.I pathname
is executed, the program exits with status 1.
Otherwise, the exit status equals to that program's exit status.
.
.SH ENVIRONMENT
.TP
.B ARIFY_FRONTEND
The frontend program to use.
.IP
If the variable is unset or empty, value "readline" will be used.
.IP
To use the Readline frontend, key bindings should be configured.
See the "Readline key bindings" subsection in NOTES for details.
.TP
.B ARIFY_ENGINES
Comma-separated list of input method engines to use.
At least one engine should be specified.
.IP
See the "Engine names" subsection in NOTES for engine name format.
.TP
.B ARIFY_LOG_FILE
Path to the file where error logs (and debug logs, if enabled)
will be written to.
.IP
If the variable is unset or empty, logs will not be printed.
.TP
.B ARIFY_PAGE_SIZE
Maximum number of candidates per page (at most 20).
.IP
If the variable is unset or empty, value 5 will be used.
.SS
Readline-only environments:
.TP
.B ARIFY_RL_NO_AUTO_UNSETENV
By default, when arify is enabled for the first time
(by invoking the
.B arify\-toggle
Readline command),
environment variables related to arify are unset, so that it won't be
initialized in child processes.
.IP
This behavior can be disabled by setting this variable to any non-empty value.
.TP
.B ARIFY_RL_WORD_BREAK_CHARS
List of characters that are supposed to signal a word break.
Overrides
.I rl_completer_word_break_characters
when arify is enabled.
.IP
If the variable is unset or empty, value " \\t\\n" will be used.
.IP
Note that the list should contain the actual characters
(i.e., escape sequences would not work).
.
.SH NOTES
.SS Engine names
Each engine name in the
.B ARIFY_ENGINES
list should comply with the following format:
.PP
.in +4n
.EX
.IR <lib_name> : <symbol_name>
.EE
.in
.PP
The
.I <lib_name>
is the path to the shared library file containing the engine implementation.
This name is used as the first argument to pass to
.BR dlopen (3).
.PP
The
.I <symbol_name>
is the name of the
.B struct arif_engine
where the engine is implemented (see
.BR arif_set_engine (3)).
This name is used as the second argument to pass to
.BR dlsym (3).
.PP
If the two names match the following pattern, a
.I <short_name>
can be used instead of the full name:
.PP
.in +4n
.EX
.IR <libdir> /libarif_ <short_name><shlib_suffix> :arif_ <short_name> _engine
.EE
.in
.PP
Where
.IR <shlib_suffix>
is the common name suffix for shared library files on the current platform
(e.g., ".so" on GNU/Linux).
.SS Readline key bindings
If using the Readline frontend, extra key bindings need to be configured in
.IR \[ti]/.inputrc :
.TP
.B arify\-toggle
Turn on/off input method engine.
.IP
When turned on, Readline's completion functions will be replaced by those
provided by ARIF.
When turned off, the previously saved completion functions will be restored.
.TP
.B arify\-engine\-info
Prints information regarding the currently active engine.
.TP
.B arify\-next\-engine
Switch to the next loaded engine.
If there are no more available engines, switch back to the first engine.
.TP
.B arify\-page\-up
.TQ
.B arify\-page\-down
Switch to previous/next page of candidates, and display them.
.PP
See EXAMPLES for an example configuration.
.
.SH EXAMPLES
.SS Example Readline configuration
The following is a simple
.IR \[ti]/.inputrc
snippet which configures key bindings for arify
when working with
.BR rlexec (1).
.PP
.in +4n
.EX
$if rlexec
    "\\e ":     arify\-toggle
    "\\e\\\\":    arify\-next\-engine
    "\\e[5;3\[ti]": arify\-page\-up      # M\-PgUp
    "\\e[6;3\[ti]": arify\-page\-down    # M\-PgDn
$endif
.EE
.in
.SH BUGS
Theoretically arify should work with most programs with a supported frontend.
However, there are situations where it may not work as expected:
.IP \[bu] 3
When
.B LD_PRELOAD
is not functioning, arify does not work.
.IP \[bu]
When a Readline program does fancy things with the Readline API (e.g.,
change handler functions during user input), arify may also fail to work,
since it may break the internal states arify maintains.
.PP
Meanwhile, adding support for more frontends may not be as simple
(or even possible) as with Readline, due to the way how arify works.
.
.SH COPYRIGHT
Copyright (C) 2023  CismonX <admin@cismon.net>
.PP
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
.PP
You should have received a copy of the license along with this document.
If not, see
.UR https://www.gnu.org/licenses/fdl-1.3.html
.UE .
.
.SH SEE ALSO
.BR rlexec (1),
.BR arif_set_engine (3),
.BR dlopen (3),
.BR dlsym (3),
.BR readline (3),
.BR ld.so (8)
