#
# Copyright (C) 2023  CismonX <admin@cismon.net>
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty, provided the copyright notice and
# this notice are preserved. This file is offered as-is, without any warranty.
#

noinst_HEADERS     = arif_defs.h arify.h
pkginclude_HEADERS = arif.h


if BUILD_ARIF_READLINE

  noinst_HEADERS     += arify_rl.h
  pkginclude_HEADERS += arif_rl.h

endif  # BUILD_ARIF_READLINE
